export const weatherAPI = '30aa08af5a9e41a1ae2114054251606';

export const weatherIcon = {
  'Partly Cloudy': require('../assets/images/partlycloudy.png'),
  'Partly Cloudy ': require('../assets/images/partlycloudy.png'),
  'Partly cloudy': require('../assets/images/partlycloudy.png'),
  'Partly cloudy ': require('../assets/images/partlycloudy.png'),
  'Moderate rain ': require('../assets/images/moderaterain.png'),
  'Moderate rain': require('../assets/images/moderaterain.png'),
  'Patchy rain possible': require('../assets/images/moderaterain.png'),
  'Patchy rain possible ': require('../assets/images/moderaterain.png'),
  'Patchy rain nearby': require('../assets/images/moderaterain.png'),
  'Patchy rain nearby ': require('../assets/images/moderaterain.png'),
  Sunny: require('../assets/images/sun.png'),
  'Sunny ': require('../assets/images/sun.png'),
  Clear: require('../assets/images/sun.png'),
  'Clear ': require('../assets/images/sun.png'),
  'Overcast ': require('../assets/images/cloud.png'),
  Overcast: require('../assets/images/cloud.png'),
  Cloudy: require('../assets/images/cloud.png'),
  'Cloudy ': require('../assets/images/cloud.png'),
  Mist: require('../assets/images/cloud.png'),
  'Mist ': require('../assets/images/cloud.png'),
  'Light rain': require('../assets/images/moderaterain.png'),
  'Light rain ': require('../assets/images/moderaterain.png'),
  'Moderate rain at times': require('../assets/images/moderaterain.png'),
  'Moderate rain at times ': require('../assets/images/moderaterain.png'),
  'Heavy rain': require('../assets/images/heavyrain.png'),
  'Heavy rain ': require('../assets/images/heavyrain.png'),
  'Heavy rain at times': require('../assets/images/heavyrain.png'),
  'Heavy rain at times ': require('../assets/images/heavyrain.png'),
  'Moderate or heavy freezing rain': require('../assets/images/heavyrain.png'),
  'Moderate or heavy freezing rain ': require('../assets/images/heavyrain.png'),
  'Moderate or heavy rain shower': require('../assets/images/heavyrain.png'),
  'Moderate or heavy rain shower ': require('../assets/images/heavyrain.png'),
  'Moderate or heavy rain with thunder': require('../assets/images/heavyrain.png'),
  'Moderate or heavy rain with thunder ': require('../assets/images/heavyrain.png'),
  Other: require('../assets/images/moderaterain.png'),
};

export const lottieAnimation = {
  'Partly Cloudy': require('../assets/animations/sunPartial.json'),
  'Partly Cloudy ': require('../assets/animations/sunPartial.json'),
  'Partly cloudy': require('../assets/animations/sunPartial.json'),
  'Partly cloudy ': require('../assets/animations/sunPartial.json'),

  'Moderate rain ': require('../assets/animations/rain.json'),
  'Moderate rain': require('../assets/animations/rain.json'),
  'Patchy rain possible': require('../assets/animations/rain.json'),
  'Patchy rain possible ': require('../assets/animations/rain.json'),
  'Patchy rain nearby': require('../assets/animations/rain.json'),
  'Patchy rain nearby ': require('../assets/animations/rain.json'),
  'Light rain': require('../assets/animations/rain.json'),
  'Light rain ': require('../assets/animations/rain.json'),
  'Moderate rain at times': require('../assets/animations/rain.json'),
  'Moderate rain at times ': require('../assets/animations/rain.json'),

  night: require('../assets/animations/night.json'),
  'night cloud': require('../assets/animations/moonPartial.json'),

  Sunny: require('../assets/animations/sun.json'),
  'Sunny ': require('../assets/animations/sun.json'),
  'Clear ': require('../assets/animations/sun.json'),
  Clear: require('../assets/animations/sun.json'),

  'Overcast ': require('../assets/animations/overcast.json'),
  Overcast: require('../assets/animations/overcast.json'),
  Cloudy: require('../assets/animations/cloud.json'),
  'Cloudy ': require('../assets/animations/cloud.json'),
  Mist: require('../assets/animations/mist.json'),
  'Mist ': require('../assets/animations/mist.json'),

  'Heavy rain': require('../assets/animations/thunder.json'),
  'Heavy rain ': require('../assets/animations/thunder.json'),
  'Heavy rain at times': require('../assets/animations/thunder.json'),
  'Heavy rain at times ': require('../assets/animations/thunder.json'),
  'Moderate or heavy freezing rain': require('../assets/animations/thunder.json'),
  'Moderate or heavy freezing rain ': require('../assets/animations/thunder.json'),
  'Moderate or heavy rain shower': require('../assets/animations/thunder.json'),
  'Moderate or heavy rain shower ': require('../assets/animations/thunder.json'),
  'Moderate or heavy rain with thunder': require('../assets/animations/thunder.json'),
  'Moderate or heavy rain with thunder ': require('../assets/animations/thunder.json'),

  Other: require('../assets/images/moderaterain.png'),
};
